source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'AWPasscodeViewController' do
  pod "AWPasscodeViewController", :path => "../"
end

target 'Tests' do
  pod "AWPasscodeViewController", :path => "../"
end
